// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {ZkNftMarketplace} from "../src/ZkNftMarketplace.sol";
import {Groth16Verifier} from "../src/Verifier.sol";

/// @dev The proof/public-signal fixtures below are REAL -- generated by
/// running the actual compiled circuit (zk/build/purchase_js) through
/// snarkjs groth16.fullProve, for one-time code at index 1 of the
/// provisioned 65,536-code batch (see zk/data/), buyer
/// 0x702AB18eF7A539AC096F0Bd6FF936f779f4A8f9c. See
/// zk/scripts/generate-proof.js to regenerate fixtures for other inputs.
contract ZkNftMarketplaceTest is Test {
    ZkNftMarketplace marketplace;
    Groth16Verifier verifier;

    address constant BUYER = 0x702AB18eF7A539AC096F0Bd6FF936f779f4A8f9c;

    // Merkle root over the 65,536 provisioned codes, from
    // zk/scripts/generate-codes.js
    uint256 constant MERKLE_ROOT =
        3086111070189334586838256502126765284377019528688403121091715452212386201437;

    uint256[2] pA = [
        0x1e6ed6fa7590bf4b81fc77aa0ceeab120772ad243921208ea0d30a0d95b03177,
        0x29e7d612325df8e138f79839c4f92bb1ea816afd4fccc44d57985bf2180350e3
    ];
    uint256[2][2] pB = [
        [
            0x15a468211dc018dd1e233535fd0ec87de4e6b11b220bd89bfd4b873fc1df14a6,
            0x001ae0c630327357d11b7b51114ba4b18ae303891bbb23b70524f9db83379274
        ],
        [
            0x28767817dcbedb5561bedd915451c3e6c5d7e4b13cab46f97660aaf8045773b3,
            0x2aaccb131773fc74cc381e204fb45e5075181d3bbf958981a7199921d788dcf7
        ]
    ];
    uint256[2] pC = [
        0x01c8c34adde6c161181c04fa60e3e422dd7efe9efe917673ad164ac4886c43fe,
        0x1906046a8044d3a4cb1d6289f1bdf4320814d8ddfc435490ad2bc3db18a4e7ab
    ];
    // [nullifier, root, buyer]
    uint256[3] pubSignals = [
        0x0061687d25edbce7dcfa3f27b2954ed6336335b030c105c6600ed28387f035f2,
        0x06d2ad4da1ec0ebcb7af2aa5fd634cbed1ad9d161bdacbf12273db97ca37ff5d,
        uint256(uint160(BUYER))
    ];

    function setUp() public {
        verifier = new Groth16Verifier();
        marketplace = new ZkNftMarketplace(
            "ZK Gated NFT",
            "ZKNFT",
            address(verifier),
            MERKLE_ROOT,
            0, // price is informational only, off-chain payment
            address(this)
        );
    }

    function test_RawVerifierAcceptsRealProof() public view {
        assertTrue(verifier.verifyProof(pA, pB, pC, pubSignals));
    }

    function test_PurchaseSucceedsWithValidProof() public {
        vm.prank(BUYER);
        uint256 tokenId = marketplace.purchase(pA, pB, pC, pubSignals);

        assertEq(tokenId, 0);
        assertEq(marketplace.ownerOf(0), BUYER);
        assertTrue(marketplace.nullifierUsed(pubSignals[0]));
    }

    function test_RevertsOnNullifierReplay() public {
        vm.prank(BUYER);
        marketplace.purchase(pA, pB, pC, pubSignals);

        vm.prank(BUYER);
        vm.expectRevert(ZkNftMarketplace.NullifierAlreadyUsed.selector);
        marketplace.purchase(pA, pB, pC, pubSignals);
    }

    function test_RevertsIfCallerIsNotProvenBuyer() public {
        address attacker = address(0xBEEF);
        vm.prank(attacker);
        vm.expectRevert(ZkNftMarketplace.BuyerMismatch.selector);
        marketplace.purchase(pA, pB, pC, pubSignals);
    }

    function test_RevertsIfAttackerSwapsBuyerSignal() public {
        // Simulates someone intercepting this valid proof and trying to
        // relabel the public `buyer` signal to their own address instead
        // of the one the proof was actually generated for. This must fail
        // proof verification itself (not just the BuyerMismatch check),
        // because the circuit's `buyerSquare <== buyer * buyer` constraint
        // cryptographically binds buyer into the proof.
        address attacker = address(0xBEEF);
        uint256[3] memory tampered = pubSignals;
        tampered[2] = uint256(uint160(attacker));

        vm.prank(attacker);
        vm.expectRevert(ZkNftMarketplace.InvalidProof.selector);
        marketplace.purchase(pA, pB, pC, tampered);
    }

    function test_RevertsOnWrongRoot() public {
        uint256[3] memory tampered = pubSignals;
        tampered[1] = pubSignals[1] + 1;

        vm.prank(BUYER);
        vm.expectRevert(ZkNftMarketplace.RootMismatch.selector);
        marketplace.purchase(pA, pB, pC, tampered);
    }
}
